#env = Environment(CPPPATH=[libnumth_path, '/usr/include/qt3'],
#                  CCFLAGS=['-g'],
#                  LIBS=['numth','qt-mt', 'pthread', 'm', 'X11', 'Xext','qttestrunner' ],
#                  LIBPATH=[libnumth_path])
#
Import('env')

def CheckCppunit(context):
  context.Message('Checking for Cppunit... ')
  ret = context.TryAction( Action('cppunit-config --libs') )
  context.Result(ret[0])
  return ret[0]

if not env.GetOption('clean'):
  conf = Configure(env, custom_tests = {'CheckCppunit':CheckCppunit} )
  if not conf.CheckCppunit():
    print 'Cppunit is not installed. Exiting...'
    Exit(1)
  env = conf.Finish()


env.ParseConfig('cppunit-config --libs')

files = Split("""
    ZTest.cpp
    main.cpp
    """)


cppunitTests = env.Program('runTests', files)
Alias('unitTests', cppunitTests)
Alias('all', cppunitTests)
