import os.path

#env = Environment(CPPPATH=[libnumth_path, '/usr/include/qt3'],
#                  CCFLAGS=['-g'],
#                  LIBS=['numth','qt-mt', 'pthread', 'm', 'X11', 'Xext','qttestrunner' ],
#                  LIBPATH=[libnumth_path])
#
Import('myenv')

myenv.Append(CPPPATH = '#/extra/include')
myenv.Append(CPPPATH = ('#/extra/include' + myenv['ARCH_BITS']))
myenv.Append(LIBPATH= ('#/extra/lib' + myenv['ARCH_BITS']))

myenv.Append(LIBS = ['qt-mt', 'pthread', 'm', 'X11', 'Xext', 'pari', 'qtunit'])
myenv.Append(CPPPATH = '/usr/include/qt3')
#myenv.Replace(CCFLAGS = '-O0 -ggdb3') #FIXME

moduleFiles = Split("""
    KernelTest.cpp
    ZTest.cpp
    RSATest.cpp
    NumthTestSuite.cpp
    TestModule.cpp
    TextRunner.cpp
    """)

textRunner = myenv.Program('textRunner', moduleFiles)

myenv.Install(myenv['INSTALL_DIR_TESTS'], textRunner)
Alias('tests', textRunner)
#Alias('tests', myenv['INSTALL_DIR_TESTS'])
Alias('all', 'tests')
Alias('install', myenv['INSTALL_DIR_TESTS'])
